# Generated by Django 3.1.7 on 2021-03-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('courier_type', models.CharField(choices=[('foot', 'foor'), ('bike', 'bike'), ('car', 'car')], max_length=20)),
                ('regions', models.CharField(default='', max_length=120)),
                ('working_hours', models.CharField(default='', max_length=240)),
            ],
        ),
    ]
