# Generated by Django 3.1.7 on 2021-03-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_type',
            field=models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=20),
        ),
    ]
