# Generated by Django 3.1.7 on 2021-03-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0005_auto_20210327_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliviery_time',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
