# Generated by Django 3.1.7 on 2021-03-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0006_order_deliviery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='earning_ratio',
            field=models.IntegerField(choices=[(2, 'foot'), (5, 'bike'), (9, 'car')], default=2),
        ),
        migrations.AddField(
            model_name='courier',
            name='earnings',
            field=models.FloatField(default=0),
        ),
    ]
