# Generated by Django 3.1.7 on 2021-03-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0007_auto_20210328_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliviery_time',
        ),
    ]
