# Generated by Django 3.1.7 on 2021-03-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0008_remove_order_deliviery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliviery_time',
            field=models.DateTimeField(null=True),
        ),
    ]
