# Generated by Django 3.1.7 on 2021-03-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0009_order_deliviery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliviery_time',
        ),
    ]
